# Generated by Django 3.2.8 on 2021-10-10 18:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Utils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Удобство',
                'verbose_name_plural': 'Удобства',
            },
        ),
        migrations.CreateModel(
            name='Advent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='')),
                ('district', models.PositiveSmallIntegerField(choices=[(1, 'АКЗ'), (2, 'РТС'), (3, 'Гора'), (4, 'Лиски'), (5, 'Центр')], verbose_name='Район')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price_per', models.PositiveSmallIntegerField(choices=[(1, 'День'), (1, 'Неделя'), (1, 'Месяц')], verbose_name='Цена за')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена (грн.)')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads.category', verbose_name='Категория')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('utils', models.ManyToManyField(blank=True, to='ads.Utils', verbose_name='Удобства')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
